module.exports = {
  DELETE_SCHEMA: 'DROP SCHEMA "public" CASCADE',
  CREATE_SCHEMA: 'CREATE SCHEMA "public"',
  CLEAR_DATABASE: `
     do
     $$
      declare
        l_stmt text;
      begin 
        select 'truncate ' || string_agg(format('%I.%I', schemaname, tablename), ',')
        into l_stmt 
        from pg_tables
        where schemaname in ('public') and 
        tablename not in ('knex_migrations', 'knex_migrations_lock', 'role');
        execute l_stmt;
      end;
      $$
  `,
  ROLES_EXISTS: `
    SELECT 
      count(*) AS count 
    FROM 
      "public"."role";
  `,
  INSERT_ROLES: `
    INSERT INTO
      "public"."role"(name) 
    VALUES ('administrator'), ('user');`,
  INSERT_ADMINISTRATOR: `
    WITH inserted_admin AS (
      INSERT INTO "public"."user" (email, first_name, last_name) VALUES ('administrator@test.com', 'Test', 'Administrator') RETURNING id
    ), inserted_admin_roles AS (
       INSERT INTO "public"."users_roles" (user_id, role_id)
           SELECT (SELECT id FROM inserted_admin), (SELECT id FROM "public"."role" WHERE name = 'administrator')
    )
    INSERT INTO "public"."security" 
    SELECT
     id,
     '9c46dbec5d03f74352cc4a4da354b4e9796887eeb66ac292617692e765dbe400352559b16229f97b27614b51dbfbbb14613f2c10350435a8feaf53f73ba01c7c',
     '9c46dbec5d03f74352cc4a4da354b4e9796887eeb66ac292617692e765dbe400352559b16229f97b27614b51dbfbbb14613f2c10350435a8feaf53f73ba01c7a',
      null,
      true,
      false,
      NOW() 
    FROM inserted_admin;`,
  INSERT_USER: `
    WITH inserted_user AS (
      INSERT INTO "public"."user" (email, first_name, last_name) VALUES ('user@test.com', 'Test', 'User') RETURNING id
    ), inserted_admin_roles AS (
       INSERT INTO "public"."users_roles" (user_id, role_id)
           SELECT (SELECT id FROM inserted_user), (SELECT id FROM "public"."role" WHERE name = 'user')
    )
    INSERT INTO "public"."security" 
    SELECT
     id,
     '9c46dbec5d03f74352cc4a4da354b4e9796887eeb66ac292617692e765dbe400352559b16229f97b27614b51dbfbbb14613f2c10350435a8feaf53f73ba01c7c',
     '9c46dbec5d03f74352cc4a4da354b4e9796887eeb66ac292617692e765dbe400352559b16229f97b27614b51dbfbbb14613f2c10350435a8feaf53f73ba01c7b',
      null,
      true,
      false,
      NOW() 
    FROM inserted_user;`,
  INSERT_COUNTRIES: `
    INSERT INTO "public"."country" (code, name, supported) VALUES 
      ('AF', 'Afghanistan', false),
      ('AL', 'Albania', false),
      ('DZ', 'Algeria', false),
      ('DS', 'American Samoa', false),
      ('AD', 'Andorra', false),
      ('AO', 'Angola', false),
      ('AI', 'Anguilla', false),
      ('AQ', 'Antarctica', false),
      ('AG', 'Antigua and Barbuda', false),
      ('AR', 'Argentina', true),
      ('AM', 'Armenia', false),
      ('AW', 'Aruba', false),
      ('AU', 'Australia', true),
      ('AT', 'Austria', true),
      ('AZ', 'Azerbaijan', false),
      ('BS', 'Bahamas', false),
      ('BH', 'Bahrain', false),
      ('BD', 'Bangladesh', false),
      ('BB', 'Barbados', false),
      ('BY', 'Belarus', false),
      ('BE', 'Belgium', true),
      ('BZ', 'Belize', false),
      ('BJ', 'Benin', false),
      ('BM', 'Bermuda', false),
      ('BT', 'Bhutan', false),
      ('BO', 'Bolivia', false),
      ('BA', 'Bosnia and Herzegovina', false),
      ('BW', 'Botswana', false),
      ('BV', 'Bouvet Island', false),
      ('BR', 'Brazil', true),
      ('IO', 'British Indian Ocean Territory', false),
      ('BN', 'Brunei Darussalam', false),
      ('BG', 'Bulgaria', false),
      ('BF', 'Burkina Faso', false),
      ('BI', 'Burundi', false),
      ('KH', 'Cambodia', false),
      ('CM', 'Cameroon', false),
      ('CA', 'Canada', false),
      ('CV', 'Cape Verde', false),
      ('KY', 'Cayman Islands', false),
      ('CF', 'Central African Republic', false),
      ('TD', 'Chad', false),
      ('CL', 'Chile', true),
      ('CN', 'China', false),
      ('CX', 'Christmas Island', false),
      ('CC', 'Cocos (Keeling) Islands', false),
      ('CO', 'Colombia', true),
      ('KM', 'Comoros', false),
      ('CG', 'Congo', false),
      ('CK', 'Cook Islands', false),
      ('CR', 'Costa Rica', true),
      ('HR', 'Croatia', true),
      ('CU', 'Cuba', false),
      ('CY', 'Cyprus', false),
      ('CZ', 'Czech Republic', true),
      ('DK', 'Denmark', true),
      ('DJ', 'Djibouti', false),
      ('DM', 'Dominica', false),
      ('DO', 'Dominican Republic', false),
      ('TP', 'East Timor', false),
      ('EC', 'Ecuador', true),
      ('EG', 'Egypt', false),
      ('SV', 'El Salvador', true),
      ('GQ', 'Equatorial Guinea', false),
      ('ER', 'Eritrea', false),
      ('EE', 'Estonia', true),
      ('ET', 'Ethiopia', false),
      ('FK', 'Falkland Islands (Malvinas)', false),
      ('FO', 'Faroe Islands', false),
      ('FJ', 'Fiji', false),
      ('FI', 'Finland', true),
      ('FR', 'France', true),
      ('GF', 'French Guiana', true),
      ('PF', 'French Polynesia', true),
      ('TF', 'French Southern Territories', false),
      ('GA', 'Gabon', false),
      ('GM', 'Gambia', false),
      ('GE', 'Georgia', false),
      ('DE', 'Germany', true),
      ('GH', 'Ghana', false),
      ('GI', 'Gibraltar', false),
      ('GK', 'Guernsey', false),
      ('GR', 'Greece', false),
      ('GL', 'Greenland', false),
      ('GD', 'Grenada', false),
      ('GP', 'Guadeloupe', true),
      ('GU', 'Guam', false),
      ('GT', 'Guatemala', false),
      ('GN', 'Guinea', false),
      ('GW', 'Guinea-Bissau', false),
      ('GY', 'Guyana', false),
      ('HT', 'Haiti', false),
      ('HM', 'Heard and Mc Donald Islands', false),
      ('HN', 'Honduras', false),
      ('HK', 'Hong Kong', true),
      ('HU', 'Hungary', true),
      ('IS', 'Iceland', false),
      ('IN', 'India', false),
      ('IM', 'Isle of Man', false),
      ('ID', 'Indonesia', false),
      ('IR', 'Iran (Islamic Republic of)', true),
      ('IQ', 'Iraq', false),
      ('IE', 'Ireland', true),
      ('IL', 'Israel', false),
      ('IT', 'Italy', true),
      ('CI', 'Ivory Coast', false),
      ('JE', 'Jersey', false),
      ('JM', 'Jamaica', false),
      ('JP', 'Japan', false),
      ('JO', 'Jordan', false),
      ('KZ', 'Kazakhstan', false),
      ('KE', 'Kenya', true),
      ('KI', 'Kiribati', false),
      ('KP', 'Korea, Democratic People''s Republic of', false),
      ('KR', 'Korea, Republic of', true),
      ('XK', 'Kosovo', false),
      ('KW', 'Kuwait', false),
      ('KG', 'Kyrgyzstan', false),
      ('LA', 'Lao People''s Democratic Republic', false),
      ('LV', 'Latvia', false),
      ('LB', 'Lebanon', false),
      ('LS', 'Lesotho', false),
      ('LR', 'Liberia', false),
      ('LY', 'Libyan Arab Jamahiriya', false),
      ('LI', 'Liechtenstein', true),
      ('LT', 'Lithuania', false),
      ('LU', 'Luxembourg', true),
      ('MO', 'Macau', false),
      ('MK', 'Macedonia', false),
      ('MG', 'Madagascar', false),
      ('MW', 'Malawi', false),
      ('MY', 'Malaysia', true),
      ('MV', 'Maldives', false),
      ('ML', 'Mali', false),
      ('MT', 'Malta', true),
      ('MH', 'Marshall Islands', false),
      ('MQ', 'Martinique', true),
      ('MR', 'Mauritania', false),
      ('MU', 'Mauritius', true),
      ('YT', 'Mayotte', true),
      ('MX', 'Mexico', true),
      ('FM', 'Micronesia, Federated States of', false),
      ('MD', 'Moldova, Republic of', false),
      ('MC', 'Monaco', false),
      ('MN', 'Mongolia', false),
      ('ME', 'Montenegro', false),
      ('MS', 'Montserrat', false),
      ('MA', 'Morocco', false),
      ('MZ', 'Mozambique', false),
      ('MM', 'Myanmar', false),
      ('NA', 'Namibia', false),
      ('NR', 'Nauru', false),
      ('NP', 'Nepal', false),
      ('NL', 'Netherlands', true),
      ('AN', 'Netherlands Antilles', false),
      ('NC', 'New Caledonia', true),
      ('NZ', 'New Zealand', true),
      ('NI', 'Nicaragua', false),
      ('NE', 'Niger', false),
      ('NG', 'Nigeria', false),
      ('NU', 'Niue', false),
      ('NF', 'Norfolk Island', false),
      ('MP', 'Northern Mariana Islands', false),
      ('NO', 'Norway', true),
      ('OM', 'Oman', true),
      ('PK', 'Pakistan', false),
      ('PW', 'Palau', false),
      ('PS', 'Palestine', false),
      ('PA', 'Panama', true),
      ('PG', 'Papua New Guinea', false),
      ('PY', 'Paraguay', false),
      ('PE', 'Peru', false),
      ('PH', 'Philippines', false),
      ('PN', 'Pitcairn', false),
      ('PL', 'Poland', false),
      ('PT', 'Portugal', true),
      ('PR', 'Puerto Rico', false),
      ('QA', 'Qatar', false),
      ('RE', 'Réunion', true),
      ('RO', 'Romania', true),
      ('RU', 'Russian Federation', false),
      ('RW', 'Rwanda', false),
      ('KN', 'Saint Kitts and Nevis', false),
      ('LC', 'Saint Lucia', false),
      ('VC', 'Saint Vincent and the Grenadines', false),
      ('WS', 'Samoa', false),
      ('SM', 'San Marino', false),
      ('ST', 'Sao Tome and Principe', false),
      ('SA', 'Saudi Arabia', false),
      ('SN', 'Senegal', false),
      ('RS', 'Serbia', false),
      ('SC', 'Seychelles', false),
      ('SL', 'Sierra Leone', false),
      ('SG', 'Singapore', true),
      ('SK', 'Slovakia', true),
      ('SI', 'Slovenia', false),
      ('SB', 'Solomon Islands', false),
      ('SO', 'Somalia', false),
      ('ZA', 'South Africa', true),
      ('GS', 'South Georgia South Sandwich Islands', false),
      ('SS', 'South Sudan', false),
      ('ES', 'Spain', true),
      ('LK', 'Sri Lanka', false),
      ('SH', 'St. Helena', false),
      ('PM', 'St. Pierre and Miquelon', false),
      ('SD', 'Sudan', false),
      ('SR', 'Suriname', false),
      ('SJ', 'Svalbard and Jan Mayen Islands', false),
      ('SZ', 'Swaziland', false),
      ('SE', 'Sweden', true),
      ('CH', 'Switzerland', true),
      ('SY', 'Syrian Arab Republic', false),
      ('TW', 'Taiwan', true),
      ('TJ', 'Tajikistan', false),
      ('TZ', 'Tanzania, United Republic of', false),
      ('TH', 'Thailand', false),
      ('TG', 'Togo', false),
      ('TK', 'Tokelau', false),
      ('TO', 'Tonga', false),
      ('TT', 'Trinidad and Tobago', false),
      ('TN', 'Tunisia', true),
      ('TR', 'Turkey', false),
      ('TM', 'Turkmenistan', false),
      ('TC', 'Turks and Caicos Islands', false),
      ('TV', 'Tuvalu', false),
      ('UG', 'Uganda', false),
      ('UA', 'Ukraine', false),
      ('AE', 'United Arab Emirates', true),
      ('GB', 'United Kingdom', true),
      ('US', 'United States', true),
      ('UM', 'United States minor outlying islands', false),
      ('UY', 'Uruguay', false),
      ('UZ', 'Uzbekistan', false),
      ('VU', 'Vanuatu', false),
      ('VA', 'Vatican City State', false),
      ('VE', 'Venezuela', false),
      ('VN', 'Vietnam', false),
      ('VG', 'Virgin Islands (British)', false),
      ('VI', 'Virgin Islands (U.S.)', false),
      ('WF', 'Wallis and Futuna Islands', false),
      ('EH', 'Western Sahara', false),
      ('YE', 'Yemen', false),
      ('ZR', 'Zaire', false),
      ('ZM', 'Zambia', false),
      ('ZW', 'Zimbabwe', false);`
};