export default {
  HEAD: 'O nama',
  TITLE: 'O nama',
  PARAGRAPH_1: 'Možda smatrate krađu bicikala manjom neugodnošću ili ne tako strašnom stvari. Međutim, ako ste se ikada našli u situaciji da vam je bicikl ukaden onda znate koliko to velika smetnja može biti u vašim dnevnim rutinama. Policija se obično bavi stvarima koje imaju viši prioritet. Zapravo policijske statistike u Zapadnoj Evropi (Danska) kažu da tek svaka stota prijava rezultuje policijskom istragom, što dalje obeshrabruje bicikliste od toga da uopšte prijave krađe.',
  PARAGRAPH_2: 'Neki regioni su više pogođeni ovim problemom neki manje ali je činjenica da je, gde god da je biciklizam rasprostranjen, uvek praćen enormnom količinom ukrdenih bicikala. Jedan od najvećih problema što se tiče prevencije krađa je taj da gradovi često i ne razumeju do koje mere je problem rasprostranjen. Samo u Danskoj (a danska je poznata kao raj za bicikliste) 17% svih građana je doživelo da im ukradu bicikl. Da bismo to stavili u kontekst reći ćemo da je to 200 bicikala dnevno. Ako ta informacija nije dovoljno šokantna pomenućemo novac. Danske osiguravajuće kuće isplaćuju oko 34.4 miliona dolara godišnjih odšteta. Ni u jednom regionu gde je biciklizam rasprostranjen stvari ne stoje bolje. Prema američkom FBI, za razliku od mnogih drugih vrsta imovine, krađe bicikala su u porastu. U SAD oko 1.5 miliona bicikala je ukradeno svake godine. U San Francisku na primer mnogi biciklisti su prihvatili da je krađa njihovih bicikala skoro neminovna, ma koliko da su dobro vezani.',
  PARAGRAPH_3: 'Mi ćemo ovo promeniti!',
  PARAGRAPH_4_HEAD: 'Kako planiramo da to uradimo?',
  PARAGRAPH_4: 'Koristimo trekere koji su otporni na vremenske uslove i koji se ne mogu lako skinuti sa bickikla na silu. Baterije naših trekera imaju izrazito dugačak životni vek i između punjenja može proći i više od godinu dana rada. Imaćete 24/7 pristup lokaciji vašeg bicikla na našem portalu i mobilnoj aplikaciji. ',
  PARAGRAPH_5: 'Naši trekeri rade globalno, tako da roaming nije nešto što bi trebalo da vas brine. Pogledaje deo "dostupnost" za više detalja.',
  PARAGRAPH_6_HEAD: 'Na koji način planiramo da pomognemo?',
  PARAGRAPH_6: 'Dobar deo nestalih bicikala, pogotovo u regijama koje se smatraju biciklističkim rajevima poput Amsterdama i Kopenhagena, nisu ukradeni zbog profita. Vrlo često su u pitanju bicikli uzeti iz zabave i obesti. Ti bicikli ne moraju biti zauvek izgubljeni. Uz to, naši uređaji će činiti bicikle težim za krađu iz razloga što će skidanje našeg uređaja na silu uzeti potencijalnom lopovu vreme koje on nema na raspolaganju.',
  PARAGRAPH_7: 'Uz te očigledne benefite naš cilj je da saradnjom sa osiguravajućim kompanijama omogućimo da se uz naš uređaj osiguraju skuplji bicikli. To bi trebalo da smanji premije osiguranja za ljude koji koriste bicikle kao svoje primarno prevozno sredstvo.'
};