export default {
  HEAD: 'About us',
  TITLE: 'About us',
  PARAGRAPH_1: 'You might consider a bicycle theft to be a minor inconvenience, or not a big deal. However, if you ever got into that kind of situation you know how big of a nuisance can that be. Police officers usually have things with higher priority to deal with. In fact police statistics in Denmark state that every 100th result in police investigation. Let alone resolving the cases. That further discourages riders from reporting later incidents.',
  PARAGRAPH_2: 'Some regions are more affected but the fact is that where ever bicycling becomes well spread theft rate skyrockets. One of the biggest problems with stopping city bike theft is that cities don\'t even understand the extent of the problem. In Denmark alone (and Denmark is considered to be a bicycle haven) 17% of all citizens got their bicycle stolen. To put that into perspective that is 200 bicycles per day. If that information is not shocking enough lets talk about money. Danish insurance companies have around $34.4 million annual claim expenses. Things don\'t go any better in any other region where cycling is popular. According to FBI, unlike many types of properties, bicycle theft rate is on the rise. In USA about 1.5 million bicycles get stolen, every year. In San Francisco for example many cyclists have accepted theft as almost inevitable, no matter how well protected their bikes are.',
  PARAGRAPH_3: 'We are about to change this!',
  PARAGRAPH_4_HEAD: 'How would we achieve that',
  PARAGRAPH_4: 'We are using trackers resistant to environmental conditions, hard to quickly force remove from the bicycle. Trackers we provide you will have unprecedented battery life longer than one year. You will have 24/7 access to your bicycle location on our portal and mobile devices.',
  PARAGRAPH_5: 'Our trackers work globally, check our availability section for more detail.',
  PARAGRAPH_6_HEAD: 'How do we plan to help?',
  PARAGRAPH_6: 'Significant percentage of bicycles, especially in cycling havens such as Amsterdam and Copenhagen, are not stolen for profit. They are often taken for joy-rides. Those bicycles don\'t have to be lost forever. Additionally, our device will make any bicycle harder to steal, because force removal of it from bicycles will take time that the potential thief do not have.',
  PARAGRAPH_7: 'Aside from that obvious benefits, our goal is to work with insurance companies, to make our device a perquisite for insuring of expensive bikes. Hopefully this step would lower insurance premium for people who use bicycles as primary way of transportation.'
};